apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    volumeMounts:
    - name: dbvol
      mountPath: /var/lib/mysql
  volumes:
  - name: dbvol
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate
